[tool.ruff]
target-version = "py312"
line-length = 88

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "ANN401",
    "COM812",
    "D",
    "EM101",
    "EM102",
    "FBT",
    "FIX002",
    "PLR2004",
    "ISC001",
    "TC003",
    "TD",
    "TRY003",
]
unfixable = [ # we don't want these to be autofixed on save
    "COM819", # conflicts with ruff format
    "F401",   # unpractical during dev
]
exclude = ["alembic"]

[tool.ruff.lint.per-file-ignores]
"tests/**.py" = [
    "ANN",
    "S101",
]

[tool.ruff.lint.flake8-pytest-style]
fixture-parentheses = false
mark-parentheses = false
parametrize-names-type = "list"

[tool.ruff.lint.isort]
force-sort-within-sections = true

[tool.mypy]
plugins = "pydantic.mypy"

files = "kovoc"
ignore_missing_imports = false
follow_imports = "normal"

disallow_any_generics = true
disallow_subclassing_any = true

disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true

no_implicit_optional = true
strict_optional = true

warn_redundant_casts = true
warn_unused_ignores = true
warn_no_return = true
warn_return_any = true
warn_unreachable = true

ignore_errors = false

strict_equality = true

show_error_context = true
show_error_codes = true

warn_unused_configs = true
